[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#solc_version = "0.8.19"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000
via_ir = false
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@selfxyz/contracts/=node_modules/@selfxyz/contracts/'
]

[rpc_endpoints]
celo_testnet = "${CELO_TESTNET_RPC_URL}"
celo_sepolia = "${CELO_SEPOLIA_RPC_URL}"
celo_mainnet = "${CELO_MAINNET_RPC_URL}"

[etherscan]
celo_testnet = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo_sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api.blockscout.com/v2/celo-sepolia/api" }
celo_mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }

